name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: |
        uv venv
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Install package
      run: |
        uv pip install .[dev]
    - name: Check lint
      run: |
        codespell .
        ruff check .
        ruff format . --diff
    - name: Check typing
      run: |
        pytype
    - name: Test
      run: |
        coverage run -m pytest
        coverage report
